spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:competitionDb
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
